### ISSUE TITLE
oneInBothClades factor wrong?

### ISSUE THREAD

**Issue by arzwa** [cecileane/WGDgc#2]
Hi, 

I think I saw an error in the code for computing the `oneInBothClades` conditioning factor. It seems the current implementation uses `log( (1-doomL)*(1-doomR) ` for the probability of non-extinction in both clades stemming from the root, however that assumes independence (i.e. let `L=not extinct left`, `R=not extinct right` than `P(L AND R) != P(L)P(R)` as assumed here, `L` and `R` are only conditionally independent given the root state). I think in the original `WGDgc` paper, equation 4 shows the correct formula, i.e. `1 - P(L) - P(R) + P(L OR R)`, so `log(1 - doomL - doomR + doom)` in the relevant lines of code (included below)

```R
[...]
else if (conditioning=="oneInBothClades"){
    ## Wrong in previous version: used the probability that a *single* lineage
    ## does not go extinct in both the left and right clade.
    ## need to account for prior distribution of # lineages at the root.
    if (isTRUE(all.equal(c(doomL,doomR),c(1,1))))
      stop("Doom probabilities are 1, cannot condition on non-extinct family in both clades.
  BD rates:",cat(exp(logLamlogMu)))
    loglik.all = sum(loglik) - nFamily * log( (1-doomL)*(1-doomR) )
    # fixit: if (useRootStateMLE), doomL and doomR vary across families:
    #        depend on estimated # lineages surviving at root. See above.
  }
[...]
```
Does this make sense, or am I confused?

**Comment by cecileane** [comment]
Yes, it makes total sense. Thanks a bunch for catching this! Link for easier reference: line 99 in [getLikGeneCount.r](https://github.com/cecileane/WGDgc/blob/925109b05091af9a999a73e1dcbecaa3910cc21c/R/getLikGeneCount.r#L99).
