### ISSUE TITLE
Error in optim(para, getLikGeneCount, input = input, geneCountData = geneCountData,  :    L-BFGS-B needs finite values of 'fn'

### ISSUE THREAD

**Issue by wuxiaopei0509** [cecileane/WGDgc#4]
Sorry to bother you, when I run the MLEGeneCount function, an error occur as the title shows,'"Error in optim(para, getLikGeneCount, input = input, geneCountData = geneCountData,  : 
  L-BFGS-B needs finite values of 'fn' "
what does the issue happen and how can I adjust my input?
My Rscript is
> tre.string = "(((((((DUH:{0,0.012045},Rhi:{0,0.00788798}):{0,0.00883043},Rhs:{0,0.0266276}):{0,0.122567},Ach:{0,0.12961}):{0,0.0203783},CSS:{0,0.106472}):{0,0.0154055},Dlo:{0,0.173063}):{0,0.0523297},Sly:{0,0.279797}):{0,0.0944824},VIT:{0,0.0944824});" 
> tre.phylo4d = read.simmap(text=tre.string)
> geneCountData <- read.table("geneCountData.txt",header = T,sep = "\t")
> MLEGeneCount(tre.phylo4d, geneCountData, mMax=NULL, geomMean=TRUE, conditioning=c("oneOrMore"),equalBDrates=FALSE, fixedRetentionRates=TRUE,startingBDrates=c(0.01, 0.02),startingQ=NULL)

Thank you very much !

**Comment by cecileane** [comment]
I'm not sure, but I see that your branch lengths are very short. Could you try to use different values for the starting birth & death rates (= duplication & loss rates)? Also, you should set an actual numerical value for the geometric mean. Don't set it to `TRUE`. Use 1.1 perhaps, or the mean number of genes per species and per family in your data.

**Comment by cecileane** [comment]
Please also see #1, which mentions a similar issue.

**Comment by zhangqiong151** [comment]
hello,xiaopei.
I wonder if you have solved the problem?
hope to your reply. @wuxiaopei0509

**Comment by wuxiaopei0509** [comment]
Sorry， I have been confused by other things these days and I think I will consider it after a few days.

**Comment by zhangqiong151** [comment]
could you please give me your  email address? I have some questions to consult you  @wuxiaopei0509

**Comment by wuxiaopei0509** [comment]
xiaopeiwunanyang@163.com. Thank you.
